version: "3"

services:

  premios:
    build: ./microservicios/premios-service
  
  perros:
    build: ./microservicios/perros-service
  
  razas:
    build: ./microservicios/razas-service
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - premios
      - perros
      - razas
      